server:
  port: 8081
  servlet:
    context-path: /cms
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dove1314
    url: jdbc:mysql://127.0.0.1:3306/sell?serverTimezone&charactorEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml